image: registry.gitlab.info.uqam.ca/inf31351/docker/base

stages:
  - build
  - test

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - bin/kover

test:
  stage: test
  script:
    - make test
